# Deze broncode is openbaar gemaakt vanwege een Woo-verzoek zodat deze 
# gericht is op transparantie en niet op hergebruik. Hergebruik van 
# de broncode is toegestaan onder de EUPL licentie, met uitzondering 
# van broncode waarvoor een andere licentie is aangegeven.
#
# Het archief waar dit bestand deel van uitmaakt is te vinden op:
#   https://github.com/MinBZK/woo-besluit-broncode-digid-app
#
# Eventuele kwetsbaarheden kunnen worden gemeld bij het NCSC via:
#   https://www.ncsc.nl/contact/kwetsbaarheid-melden
# onder vermelding van "Logius, openbaar gemaakte broncode DigiD-App" 
#
# Voor overige vragen over dit Woo-besluit kunt u mailen met open@logius.nl
#
# This code has been disclosed in response to a request under the Dutch
# Open Government Act ("Wet open Overheid"). This implies that publication 
# is primarily driven by the need for transparence, not re-use.
# Re-use is permitted under the EUPL-license, with the exception 
# of source files that contain a different license.
#
# The archive that this file originates from can be found at:
#   https://github.com/MinBZK/woo-besluit-broncode-digid-app
#
# Security vulnerabilities may be responsibly disclosed via the Dutch NCSC:
#   https://www.ncsc.nl/contact/kwetsbaarheid-melden
# using the reference "Logius, publicly disclosed source code DigiD-App" 
#
# Other questions regarding this Open Goverment Act decision may be
# directed via email to open@logius.nl
#
# ===================================================================================================
#
# Beschrijving:
#   DIG_Mobile-BuildAll-pipeline.yml
#
# ===================================================================================================


trigger:
  batch: true
  branches:
    include:
     - master
     - main
     - TST
     - ACC
     - PP
     - PROD

#
# Gebruik een MS-Hosted machine
pool:
  vmImage: 'macOS-latest'

variables:
  #
  # Algemene instellingen
  cfg_Debug                    : "false"

  #
  # Sonarcloud connection details
  cfg_SonarConnectionName      : "BDMCC SonarCloud connection"
  cfg_SonarProjectName         : "$(System.TeamProject)"
  cfg_SonarKey                 : "DIG_Mobile"  

  #
  # AppCenter connections details
  cfg_AppCenterConnectionName  : "BDMCC AppCenter connection"

resources:
  #
  # self:     Als je repostitory resources gebruikt, dan moet je 'self' expliciet ook uit checken!
  # repo_tpl: Standaard repo met pipeline templates en scripts includen in deze pipeline
  repositories:
  - repository: self
  - repository: repo_tpl
    type: git
    name: "MCC - Ontwikkelstraat/MCC-PipelineTemplatesScripts"
    ref: "productie"
                               
steps:
#
# Zie ook: https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema?view=azure-devops&tabs=schema%2Cparameter-schema#checkout
- checkout: self
  submodules: true
  persistCredentials: true  
  path: src

#
# Deze repo bevat alle pipeline templates en noodzakelijke scripts
- checkout: repo_tpl
  path: tpl

#
# 'mcc-build-all.yml' is de start template voor het builden van MCC Apps.
- template: tpl/mcc-build-all.yml@repo_tpl
  parameters:    
      DBG: ${{ variables['cfg_Debug'] }}      

#
# Pipeline done.
